add-controllers
Natal1a-Chuklina/java-shareit pull request #2
Opened 2023-04-17 07:26 UTC by Natal1a-Chuklina

2023-04-18 03:16 UTC, z8q requested changes

2023-04-18 03:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +                .count();
Тут не обязательно считать все случаи, достаточно поймать один

2023-04-19 05:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    long currentId;
Добавила :)

2023-04-19 05:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +                .count();
Переделала.

2023-04-20 05:23 UTC, z8q approved these changes

2023-04-21 11:59 UTC, merged