реализован основной функционал ТЗ 15, добавлены тесты для проверки во…
Natal1a-Chuklina/java-shareit pull request #4
Opened 2023-05-19 14:24 UTC by Natal1a-Chuklina

2023-05-25 20:51 UTC, z8q requested changes

2023-05-25 20:51 UTC, z8q commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +class BookingServiceImplTest {
Тесты написаны подробно.
Можно было бы еще попробовать `реализовать тесты для работы с JSON для DTO в вашем приложении с помощью аннотации @JsonTest для какой-нибудь dto` – это из ТЗ

2023-05-26 08:15 UTC, Natal1a-Chuklina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +class BookingServiceImplTest {
Добавила)

2023-05-27 05:14 UTC, z8q approved these changes

2023-05-29 15:21 UTC, merged