разнесены сервисы, добавлены настройки для запуска приложения в docke…
Natal1a-Chuklina/java-shareit pull request #5
Opened 2023-05-30 18:10 UTC by Natal1a-Chuklina

2023-05-31 19:16 UTC, z8q requested changes

2023-05-31 19:16 UTC, z8q commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private void checkTimeCorrectness(LocalDateTime start, LocalDateTime end) {
checkTimeCorrectness и getSearchingState можно было бы вынести из класса контроллеров для большей красоты)

2023-05-31 19:16 UTC, z8q commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void validateUser(UserDto user) {
Вот это тоже в какие-нибудь Utils можно было бы вынести

2023-06-01 09:43 UTC, Natal1a-Chuklina commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void validateUser(UserDto user) {
Вынесла)

2023-06-01 09:43 UTC, Natal1a-Chuklina commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private void checkTimeCorrectness(LocalDateTime start, LocalDateTime end) {
Вынесла

2023-06-02 10:35 UTC, z8q approved these changes

2023-06-02 12:13 UTC, merged